config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"
  
    resources :users, :historys
      
    get "/login", to: "sessions#new", as: "login"
    get "/logout", to: "sessions#destroy"
    post "/login", to: "sessions#create"
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :historys

  def self.confirm(params)
		@user = User.find_by({email: params[:email]})
		@user.try(:authenticate, params[:password])
	end
  
  def is_authorized?
    current_user == @user  
  end

  validates :name, presence: true
  validates :email, presence: true
  validates_uniqueness_of :email
  validates :email, format: {with: /@/}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
  
  def set_user
    @user = current_user	
  end
  
end

app/controllers/historys_controller.rb
class HistorysController < ApplicationController

  before_action :logged_in?, only: [:edit, :update]
  before_action :set_history, only: [:show, :edit, :update]

  def index
    @historys = History.all
  end

  def new
  end

  def create
    @history = History.new(history_params)
    @history.user = current_user
    @history.save
    redirect_to root_path
  end

  def show
    @history = History.find_by_id(params[:id])
  end

  def edit
  end

  def update
    current_params = params.require(:history).permit(:credit)
    @history.update_attributes(current_params)
    redirect_to history_path
  end

  def destroy
    @history = History.find_by_id(params[:id])
    @history.destroy
    redirect_to root_path
  end

  private

  def history_params
    params.require(:history).permit(:credit)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:notice] = "Succesfully logged in."
      redirect_to root_path
    else
      flash[:error] = "Incorrect email or password."
      redirect_to login_path
    end
  end

  def destroy
    logout
    flash[:notice] = "Succesfully logged out."
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in?, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to new_history_path
    else
      flash[:error] = "Email has already been taken"
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def edit
  end

  def update
    current_params = params.require(:user).permit(:name, :password, :email)
    @user.update_attributes(current_params)
    redirect_to user_path
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/historys_helper.rb
module HistorysHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    if current_user == nil
      redirect_to new_session_path 
    end
  end

  def logged_out?
    if current_user != nil
      redirect_to user_path(current_user)
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def authorized?(user)
    current_user == user
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/historys/new.html.erb
<div class="page">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= form_for :history, url: historys_path do |f| %>
        <fieldset>
          <h1 class="text-center">Get your first 100 credits!</h1>

          <%= f.hidden_field :credit, value: 100, class: "form-control" %><br>

          <div class="form-group">
            <div class="col-md-12">
              <%= f.submit "Sign up", class: "btn btn-success" %>
            </div>
          </div>
          
        </fieldset>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mobius</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 <!-- NAVBAR -->

  <div class="container" id="center-content">
  <br>
    <%# <nav class="navbar navbar-default navbar-fixed-top"> %>

      <ul class="nav justify-content-end">
        <li class="nav-link navbar-brand"><%= link_to "Home", root_path%></li>
        <% if current_user %>
          <li class="nav-link"><%= link_to "Profile", user_path(current_user) %></li>
          <li class="nav-link"><%= link_to "Log Out", logout_path %></li>
        <% else %>
          <li class="nav-link"><%= link_to "Signup", new_user_path %></li>
          <li class="nav-link"><%= link_to "Log In", login_path %></li>
        <% end %>     
      </ul>
    <%# </nav> %>
  </div>
  <br>
  <div>
    <% flash.each do |name, msg| %>
      <div id="flash_messages">
      <br>
        <div class="alert alert-info" role="alert">
          <%= msg %>
        </div>
      </div>
    <% end %>
  </div>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="container">
  <h1>Mobius Code Challenge</h1>
</div>

<div class="container">
  <% if current_user %>

  <h2>Welcome <%= current_user.name %>! You have ... credits avaliable.</h2>

  <h4>Send credits to other users</h4>

  <% form_for :history, url: historys_path do |f| %>
  
  <% end %>

    <% @users.each do |d| %>
      <div class="row">
        <div class="col-md-4">
          <p><%= d.name %></p>
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
          <%= button_to "Send Credits"%>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="page">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= form_for :user, url: users_path do |f| %>
        <fieldset>
          <h1 class="text-center">Sign Up!</h1>

          <div class="form-group">
            <label class="col-md-4 control-label" for="name">Name</label>
            <div class="col-md-8">
              <%= f.text_field :name, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="email">Email</label>
            <div class="col-md-8">
              <%= f.text_field :email, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="password">Password</label>
            <div class="col-md-8">
              <%= f.password_field :password, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="password_confirmation">Confirm Password</label>
            <div class="col-md-8">
              <%= f.password_field :password_confirmation, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-12">
              <%= f.submit "Sign up", class: "btn btn-success" %>
            </div>
          </div>
          
        </fieldset>
      <% end %>

    </div>
  </div>
</div>